version: '3'

networks:
    laravel:

services:
    webserver:
        container_name: booking.com_webserver
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - ${DOCKER_SERVER_PORT}:80
        volumes:
            - .:/var/www/html/project:delegated
        depends_on:
            - php
            - database_server
        networks:
            - laravel

    database_server:
        container_name: booking.com_database
        image: mysql:8
        restart: unless-stopped
        volumes:
            - ${DOCKER_DATABASE_VOLUME}:/var/lib/mysql
        tty: true
        ports:
            - ${DOCKER_DB_PORT}:3306
        environment:
            MYSQL_HOST: ${DB_HOST}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
    phpmyadmin:
        container_name: booking.com_phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - database_server
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel

    php:
        container_name: booking.com_php
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www/html/project:delegated
        networks:
            - laravel
